# Generated by Django 4.1.2 on 2025-09-10 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name of the appraisal category', max_length=100, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(help_text='Abbreviated form (e.g., code or acronym)', max_length=20, unique=True, verbose_name='Short Name')),
                ('display_name', models.CharField(help_text='User-friendly name shown in UI', max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Optional details about this appraisal category', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Appraisal Category',
                'verbose_name_plural': 'Appraisal Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Appraisal Type Name', max_length=50, verbose_name='Appraisal Type Name')),
                ('display_name', models.CharField(default='Appraisal Display Name', max_length=50, verbose_name='Display Name')),
                ('short_name', models.CharField(default='AT', max_length=5, verbose_name='Short Name of Appraisal Type')),
                ('domain_name', models.CharField(default='Appraisal Domain Name', max_length=50, verbose_name='Domain Name')),
                ('domain_description', models.CharField(default='Appraisal Type Description', max_length=100, verbose_name='Appraisal Domain Description')),
                ('domain_weight', models.FloatField(default=100.0, help_text='Percentage weight indicating importance of this domain', verbose_name='Domain Weight (%)')),
                ('at_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='appraisal.appraisalcategory', verbose_name='Appraisal Category')),
                ('at_departments', models.ManyToManyField(blank=True, related_name='appraisal_departments', to='accounts.department', verbose_name='Departments')),
                ('at_institutes', models.ManyToManyField(blank=True, related_name='appraisal_institutes', to='accounts.institute', verbose_name='Institutes')),
                ('at_job_categories', models.ManyToManyField(related_name='appraisal_types', to='accounts.jobcategory', verbose_name='Job Categories')),
                ('at_subjects', models.ManyToManyField(blank=True, related_name='appraisal_subjects', to='accounts.subject', verbose_name='Appraisal Subjects')),
                ('at_wings', models.ManyToManyField(blank=True, related_name='appraisal_wings', to='accounts.wing', verbose_name='Wings')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSelectionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('short_name', models.CharField(max_length=50, verbose_name='Short Name')),
                ('default_value', models.BooleanField(default=False, verbose_name='Default Value')),
                ('description', models.CharField(default='Appraisal Schedule Description', max_length=100, verbose_name='Appraisal Schedule Description')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Option Set Name')),
            ],
            options={
                'verbose_name': 'Option Set',
                'verbose_name_plural': 'Option Sets',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Scale Name')),
                ('description', models.TextField(blank=True, verbose_name='Scale Description')),
            ],
            options={
                'verbose_name': 'Scale',
                'verbose_name_plural': 'Scales',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Option Text')),
                ('value', models.IntegerField(verbose_name='Option Value')),
                ('option_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='appraisal.optionset')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['option_set', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(default='Default item question.', verbose_name='Item Question')),
                ('option_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appraisal.optionset')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appraisal.scale')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='EmpSelectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False, verbose_name='Criteria Value')),
                ('description', models.CharField(default='Employee Selection Description', max_length=100, verbose_name='Employee Selection Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('appraisal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_selection_data', to='appraisal.appraisaltype')),
                ('emp_selection_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_selection_data', to='appraisal.empselectioncriteria')),
            ],
        ),
        migrations.AddField(
            model_name='appraisaltype',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_scale', to='appraisal.scale', verbose_name='Appraisal Scale'),
        ),
        migrations.CreateModel(
            name='AppraisalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(default='Appraisal Schedule Description', max_length=100, verbose_name='Appraisal Schedule  Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_schedules', to='accounts.academicyear')),
                ('appraisal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appraisal.appraisaltype')),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalDataItemWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='Appraisal No')),
                ('max_score', models.PositiveIntegerField(verbose_name='Maximum Score')),
                ('obt_score', models.PositiveIntegerField(verbose_name='Obtained Score')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('appraisal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='appraisal.appraisaltype', verbose_name='Appraisal Type')),
                ('appraisal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='accounts.academicyear', verbose_name='Appraisal Year')),
                ('emp_institute', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='accounts.institute', verbose_name='Employee Institute')),
                ('emp_job_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='accounts.jobcategory', verbose_name='Employee Job Category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='accounts.employee', verbose_name='Employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_entries', to='appraisal.item', verbose_name='Item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemwise_appraisals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appraisal Data',
                'verbose_name_plural': 'Appraisal Data',
                'ordering': ['appraisal_year', 'appraisal_type', 'employee', 'appraisal_no', 'item'],
            },
        ),
        migrations.CreateModel(
            name='TotalAppraisalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_no', models.PositiveIntegerField(editable=False, null=True)),
                ('max_score', models.FloatField(default=0)),
                ('obt_score', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('appraisal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_appraisals', to='appraisal.appraisaltype')),
                ('appraisal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_appraisals', to='accounts.academicyear')),
                ('emp_institute', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='total_appraisals', to='accounts.institute', verbose_name='Employee Institute')),
                ('emp_job_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ttal_appraisals', to='accounts.jobcategory', verbose_name='Employee Job Category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_appraisals', to='accounts.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_appraisals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Total Appraisal Data',
                'verbose_name_plural': 'Total Appraisal Data',
                'ordering': ['employee', 'appraisal_year', 'appraisal_type', 'appraisal_no'],
                'unique_together': {('appraisal_year', 'appraisal_type', 'employee', 'appraisal_no')},
            },
        ),
        migrations.AddConstraint(
            model_name='empselectiondata',
            constraint=models.UniqueConstraint(fields=('appraisal_type', 'emp_selection_criteria'), name='uniq_emp_sel_per_year_type_crit'),
        ),
        migrations.AlterUniqueTogether(
            name='appraisaldataitemwise',
            unique_together={('appraisal_year', 'appraisal_type', 'employee', 'appraisal_no', 'item')},
        ),
    ]
