# Generated by Django 4.1.2 on 2025-09-16 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_appexcludedemp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppExcludedEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_emps', to='accounts.academicyear')),
                ('appraisal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_emps', to='appraisal.appraisaltype')),
                ('ex_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_records', to='accounts.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_emps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excluded Employee',
                'verbose_name_plural': 'Excluded Employees',
                'unique_together': {('academic_year', 'appraisal_type', 'ex_employee')},
            },
        ),
    ]
