# Generated by Django 4.1.2 on 2025-09-10 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_types',
            field=models.ManyToManyField(blank=True, related_name='userprofile_app_types', to='appraisal.appraisaltype', verbose_name='App Types'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app_wings',
            field=models.ManyToManyField(blank=True, related_name='userprofile_app_wings', to='accounts.wing', verbose_name='Wings'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inspection_categories',
            field=models.ManyToManyField(blank=True, related_name='userprofile_inspection_categories', to='accounts.jobcategory', verbose_name='Inspection Categories'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inspection_departments',
            field=models.ManyToManyField(blank=True, related_name='userprofile_inspection_departments', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inspection_institutes',
            field=models.ManyToManyField(blank=True, related_name='userprofile_inspection_institutes', to='accounts.institute', verbose_name='Inspection Institutes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inspection_subjects',
            field=models.ManyToManyField(blank=True, related_name='userprofile_inspection_subjects', to='accounts.subject', verbose_name='Inspection Subjects'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inspection_types',
            field=models.ManyToManyField(blank=True, related_name='userprofile_inspection_types', to='appraisal.appraisaltype', verbose_name='Inspection Domains'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inspection_wings',
            field=models.ManyToManyField(blank=True, related_name='userprofile_inspection_wings', to='accounts.wing', verbose_name='Inspection Wings'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_departments',
            field=models.ManyToManyField(blank=True, related_name='userprofile_departments', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='User Groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_institutes',
            field=models.ManyToManyField(blank=True, related_name='userprofile_institutes', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_subjects',
            field=models.ManyToManyField(blank=True, related_name='userprofile_subjects', to='accounts.subject', verbose_name='User Subjects'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_wings',
            field=models.ManyToManyField(blank=True, related_name='userprofile_wings', to='accounts.wing'),
        ),
        migrations.AddField(
            model_name='usermenupermission',
            name='menu',
            field=models.ForeignKey(help_text='Select the menu item the User can access.', on_delete=django.db.models.deletion.CASCADE, to='accounts.menu', verbose_name='Menu Item'),
        ),
        migrations.AddField(
            model_name='usermenupermission',
            name='user',
            field=models.ForeignKey(help_text='Select the user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User '),
        ),
        migrations.AddField(
            model_name='usergroupmenupermission',
            name='group',
            field=models.ForeignKey(help_text='Select the user group.', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='User Group'),
        ),
        migrations.AddField(
            model_name='usergroupmenupermission',
            name='menu',
            field=models.ForeignKey(help_text='Select the menu item the group can access.', on_delete=django.db.models.deletion.CASCADE, to='accounts.menu', verbose_name='Menu Item'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a parent menu for submenus (leave blank for main menus).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='accounts.menu', verbose_name='Parent Menu'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='accounts.jobcategory'),
        ),
        migrations.AddField(
            model_name='institute',
            name='departments',
            field=models.ManyToManyField(to='accounts.department', verbose_name='Departments'),
        ),
        migrations.AddField(
            model_name='institute',
            name='wings',
            field=models.ManyToManyField(blank=True, to='accounts.wing', verbose_name='Wings'),
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.employmentstatus', verbose_name='Employment Status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='institutes',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_categories',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.jobcategory'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='employee',
            name='teaching_posts',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.jobpost'),
        ),
        migrations.AddField(
            model_name='employee',
            name='wings',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.wing', verbose_name='Employee Wings'),
        ),
        migrations.AddField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(to='accounts.course', verbose_name='Courses'),
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='accounts.subject', verbose_name='Subjects'),
        ),
        migrations.AddField(
            model_name='appexcludedemp',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_emps', to='accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='appexcludedemp',
            name='appraisal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_emps', to='appraisal.appraisaltype'),
        ),
        migrations.AddField(
            model_name='appexcludedemp',
            name='ex_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_records', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='appexcludedemp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_emps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together={('user', 'setting')},
        ),
        migrations.AlterUniqueTogether(
            name='usermenupermission',
            unique_together={('user', 'menu')},
        ),
        migrations.AlterUniqueTogether(
            name='usergroupmenupermission',
            unique_together={('group', 'menu')},
        ),
        migrations.AlterUniqueTogether(
            name='jobpost',
            unique_together={('category', 'post_name')},
        ),
        migrations.AlterUniqueTogether(
            name='appexcludedemp',
            unique_together={('academic_year', 'appraisal_type', 'ex_employee')},
        ),
    ]
