# Generated by Django 4.1.2 on 2025-09-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppExcludedEmp',
        ),
    ]
